// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PokemonApi.Data;

#nullable disable

namespace PokemonApi.Migrations
{
    [DbContext(typeof(PokemonContext))]
    [Migration("20250625180609_RenamedUserPokemonTable")]
    partial class RenamedUserPokemonTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PokemonApi.Models.Pokemon", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("GifUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Pokedex")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Pokemon");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            GifUrl = "/imgs/squirtlegif.gif",
                            ImageUrl = "/imgs/squirtle.webp",
                            Name = "Squirtle",
                            Pokedex = "/imgs/squirtlepokedex.png",
                            Summary = "In the Pokémon anime, Squirtles origin story involves a group of abandoned Squirtle known as the Squirtle Squad, who initially cause trouble before becoming firefighters. Ash encounters this group and eventually catches the Squirtle who leads the squad, who becomes a valuable member of his team."
                        },
                        new
                        {
                            Id = 2,
                            GifUrl = "/imgs/wargif.gif",
                            ImageUrl = "/imgs/wartortlegif.gif",
                            Name = "Wartortle",
                            Pokedex = "/imgs/wartortlepokedex.webp",
                            Summary = "Notably, Ashs Squirtle, the leader of the Squirtle Squad, evolves into a Wartortle in a heartwarming moment. This evolution takes place after they participate in a firefighting competition, where Ashs Squirtle leads the Squirtle Squad to victory and decides to stay with them for further training as elite firefighters."
                        },
                        new
                        {
                            Id = 3,
                            GifUrl = "/imgs/mimikyuucard.gif",
                            ImageUrl = "/imgs/mimikyu.png",
                            Name = "Mimikyuu",
                            Pokedex = "/imgs/mimipokedex.jpg",
                            Summary = "Mimikyu is introduced as a lonely Pokémon who disguises itself as Pikachu to befriend humans, as its true form is said to be so terrifying that seeing it can cause death or illness. Mimikyus backstory, as portrayed in the anime series \"Sun & Moon\", revolves around its desire for connection and its fear of its own appearance."
                        },
                        new
                        {
                            Id = 4,
                            GifUrl = "/imgs/sableeyecard.gif",
                            ImageUrl = "/imgs/sableye.png",
                            Name = "Sableye",
                            Pokedex = "/imgs/sablepokedex.png",
                            Summary = "In the anime, Sableye has appeared in several episodes, often as a creature that enjoys playing tricks on people. In one instance, a Sableye befriends a group of people, highlighting the connection to the imps desire for friendship. Another episode shows a Sableye being tricked by Team Rocket, further emphasizing its vulnerability and desire for connection."
                        },
                        new
                        {
                            Id = 5,
                            GifUrl = "/imgs/osho.gif",
                            ImageUrl = "/imgs/oshowat.gif",
                            Name = "Oshawott",
                            Pokedex = "/imgs/oshowatpokedex.webp",
                            Summary = "Oshawott is a brave and playful Water-type Pokémon known for its strong sense of justice. In the anime, it’s loyal and determined but can be a little stubborn at times. Despite its small size, Oshawott faces challenges head-on and grows into a reliable and caring friend."
                        },
                        new
                        {
                            Id = 6,
                            GifUrl = "/imgs/munchlaxcard.gif",
                            ImageUrl = "/imgs/munchlax.gif",
                            Name = "Munchlax",
                            Pokedex = "/imgs/munchpokedex.webp",
                            Summary = "Munchlax is a laid-back and always-hungry Pokémon with a big heart. It’s a bit clumsy and loves to snack, but it’s also very loyal and caring toward its friends. In the anime, Munchlax’s easygoing nature hides its surprising strength and determination when needed."
                        },
                        new
                        {
                            Id = 7,
                            GifUrl = "/imgs/snorlaxgif.gif",
                            ImageUrl = "/imgs/snorlax.gif",
                            Name = "Snorlax",
                            Pokedex = "/imgs/snorlaxpokedex.webp",
                            Summary = "Snorlax is a gentle giant known for its love of sleep and huge appetite. Despite being calm and easygoing most of the time, it can be surprisingly strong and protective when its friends are in trouble. In the anime, Snorlax’s relaxed nature hides a powerful and loyal Pokémon."
                        },
                        new
                        {
                            Id = 8,
                            GifUrl = "/imgs/gigsnorlaxcard.gif",
                            ImageUrl = "/imgs/gigsnorlax.webp",
                            Name = "Giga Snorlax",
                            Pokedex = "/imgs/gigsnorlaxpokedex.webp",
                            Summary = "Gigantamax Snorlax is a massive and even more relaxed version of Snorlax, known for its enormous size and unstoppable appetite. While it still loves to nap, its Gigantamax form gives it incredible strength and power in battles. Despite its size, it remains a calm and loyal friend who protects those it cares about."
                        },
                        new
                        {
                            Id = 9,
                            GifUrl = "/imgs/blastcard.gif",
                            ImageUrl = "/imgs/Blast.gif",
                            Name = "Blastoise",
                            Pokedex = "/imgs/blastpokedex.png",
                            Summary = "Blastoise is a strong and dependable Water-type Pokémon known for its powerful water cannons. Calm and confident, it’s a natural protector and leader in battle. In the anime, Blastoise is loyal and brave, always ready to defend its friends with strength and skill."
                        });
                });

            modelBuilder.Entity("User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("UserId");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("UserPokemon", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("PokemonId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PokemonId");

                    b.HasIndex("UserId");

                    b.ToTable("UserPokemon", (string)null);
                });

            modelBuilder.Entity("UserPokemon", b =>
                {
                    b.HasOne("PokemonApi.Models.Pokemon", "Pokemon")
                        .WithMany()
                        .HasForeignKey("PokemonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("User", "User")
                        .WithMany("UserPokemons")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pokemon");

                    b.Navigation("User");
                });

            modelBuilder.Entity("User", b =>
                {
                    b.Navigation("UserPokemons");
                });
#pragma warning restore 612, 618
        }
    }
}
